---
title: Convierte gráficos {ggplot2} en visualizaciones interactivas con {ggiraph}
author: Bastián Olea Herrera
date: '2025-10-22'
draft: true
slug: []
categories:
  - Tutoriales
tags:
  - visualización de datos
format:
  hugo-md:
    output-file: index
    output-ext: md
excerpt:
links: 
  - icon: registered
    icon_pack: fas
    name: ggiraph
    url: https://davidgohel.github.io/ggiraph/
  - icon: github
    icon_pack: fab
    name: código
    url: https://davidgohel.github.io/ggiraph/
---

`{ggiraph}` es un paquete de R que permite agregar interactividad a gráficos {ggplot2}. Al agregar interactividad puedes hacer que tus gráficos muestren información extra al pasar el cursor encima, hacer que se destaquen u oculten elementos al pasar el cursor, hacer clic en elementos para generar cambios en aplicaciones, y más.

Otro beneficio de `{ggiraph}` es que, a diferencia de opciones como `{plotly}` o `{highcharter}`, **no necesitas aprender a usar un paquete de visualización nuevo**, porque `{ggiraph}` usa los gráficos generados por `{ggplot2}` y **mantiene al 100% su apariencia**. Esto significa que tu gráfico interactivo se verá idéntico a tu gráfico de `{ggplot2}` (a diferencia de soluciones como `ggplotly()`). Esto es gracias a que `{ggiraph}` toma el gráfico que hiciste y lo genera en `SVG`, un formato de imagen vectorial que es compatible con HTML y CSS, lo que permite la interactividad.


{{< embed "Sitio" "https://z3tt.github.io/ggiraph-user-2025/slides.html#/title-slide" >}}


## Recursos

- [Libro de `{ggiraph}`](http://ardata.fr/ggiraph-book/), por David Gohel
- Diapositivas: [Plot Twist. Adding Interactivity to the Elegance of {ggplot2} with {ggiraph}](https://z3tt.github.io/ggiraph-user-2025/slides.html#/title-slide), por Tanya Shapiro y Cédric Scherer