---
title: Sugerencias y autocompletado de código con GitHub Copilot
author: Bastián Olea Herrera
date: '2025-06-09'
slug: []
categories: []
draft: true
format:
  hugo-md:
    output-file: "index"
    output-ext: "md"
tags:
  - consejos
  - inteligencia artificial
---

Uno de beneficios concretos de la fiebre por la inteligencia artificial son las herramientas de autocompletado de código. Resulta que todas las décadas de colaboración desinteresada y proyectos de código abierto en plataformas como GitHub, de preguntas y respuestas en StackOverflow, y miles de blogs de desarrolladores solidarios, terminaron siendo una mina de oro para entrenar modelos de lenguaje. Producto de la anterior es que hoy proliferan herramientas de inteligencia artificial con abundantes conocimientos de programación.

Una de estas herramientas es GitHub Copilot, la cual puede **integrarse directamente en RStudio** para ayudarte a programar en R.

Instalación

En las opciones globales de RStudio 

¿Cómo funciona? 

Luego de activar esta herramienta, simplemente empiezas a programar, y cada vez que te detengas, el modelo intentará autocompletar lo que estés escribiendo. Frente a tu cursor aparecerá una sugerencia de código basada en lo que ya hayas escrito y en los contenidos de tu script. El modelo es capaz de **predecir lo que quieres programar**, según el lugar en el documento en que estés. Presionando la tecla _tabulador_ podrás aceptar la sugerencia e incluirla instantáneamente en tu código.

En la práctica, esto te hará **ahorrar tiempo programando tareas simples y repetitivas**, ya que en la mayoría de estos casos el modelo logrará adivinar lo que intentas hacer. Pero si intentas hacer algo fuera de lo común o demasiado específico, usualmente el modelo se queda atrás.

La herramienta **funciona mucho mejor si es que agregas comentarios a tu código**, ya sea indicando paso por paso a lo que intentas hacer, o antecediendo los bloques de código con un comentario que describa tu objetivo. Incluso, muchas veces basta con escribir un comentario con lo que intentas hacer para que el modelo lo haga por ti.

También tienes la opción de **permitir que el modelo tenga acceso a todos los archivos de tu proyecto.** Esto mejora significativamente las sugerencias que te hace el modelo, ya que le entrega una mayor comprensión de lo que intentas hacer.

Luego de varias semanas utilizándolo, puedo decir que los resultados suelen ser muy positivos.