---
title: Tips para explorar datos con R
author: Bastián Olea Herrera
date: '2025-12-03'
slug: []
categories: []
draft: true
tags:
  - estadísticas
  - básico
format:
  hugo-md:
    output-file: index
    output-ext: md
excerpt: "Por medio de la exploración de datos obtenemos las primeras ideas sobre la información que vamos a abordar. Set de un paso muy importante para poder planificar tempranamente los pasos a seguir en tu análisis, así como detectar a tiempo posibles problemas o dificultades. Por eso te voy a entregar algunas ideas para poder explorar datos de forma rápida y clara."
---

Por medio de la exploración de datos obtenemos las primeras ideas sobre la información que vamos a abordar. Set de un paso muy importante para poder planificar tempranamente los pasos a seguir en tu análisis, así como detectar a tiempo posibles problemas o dificultades. Por eso te voy a entregar algunas ideas para poder explorar datos de forma rápida y clara.



```{r}
# install.packages("skimr")
library(skimr)

skim(iris)

iris |>
  dplyr::group_by(Species) |>
  skim()
```



```{r}
ggplot2::qplot(Sepal.Length, data = iris, geom = "histogram")

library(ggplot2)

ggplot(iris) +
  aes(Sepal.Length) +
  geom_histogram()

```

```{r}
library(GGally)

iris |> 
 ggpairs(aes(color = Species)) + 
  theme_minimal() +
  scale_color_brewer(palette = "Purples", aesthetics = c("color", "fill"))
```

[Florencia Mangini](https://www.thinkingondata.com/how-to-show-correlations-between-variables/)