library(pointblank)

agent <-
  create_agent(
    tbl = ~datasets::iris,
    actions = action_levels(
      warn_at = 0.05,
      stop_at = 0.10
    ),
    tbl_name = "~datasets::iris",
    label = "Validation plan generated by `draft_validation()`."
  ) %>%
  # Expect that column `Sepal.Length` is of type: numeric
  col_is_numeric(
    columns = c("Sepal.Length")
  ) %>%
  # Expect that values in `Sepal.Length` should be between `4.3` and `7.9`
  col_vals_between(
    columns = c("Sepal.Length"),
    left = 4.3,
    right = 7.9
  ) %>%
  # Expect that column `Sepal.Width` is of type: numeric
  col_is_numeric(
    columns = c("Sepal.Width")
  ) %>%
  # Expect that values in `Sepal.Width` should be between `2` and `4.4`
  col_vals_between(
    columns = c("Sepal.Width"),
    left = 2,
    right = 4.4
  ) %>%
  # Expect that column `Petal.Length` is of type: numeric
  col_is_numeric(
    columns = c("Petal.Length")
  ) %>%
  # Expect that values in `Petal.Length` should be between `1` and `6.9`
  col_vals_between(
    columns = c("Petal.Length"),
    left = 1,
    right = 6.9
  ) %>%
  # Expect that column `Petal.Width` is of type: numeric
  col_is_numeric(
    columns = c("Petal.Width")
  ) %>%
  # Expect that values in `Petal.Width` should be between `0.1` and `2.5`
  col_vals_between(
    columns = c("Petal.Width"),
    left = 0.1,
    right = 2.5
  ) %>%
  # Expect that column `Species` is of type: factor
  col_is_factor(
    columns = c("Species")
  ) %>%
  # Expect that column schemas match
  col_schema_match(
    schema = col_schema(
      Sepal.Length = "numeric",
      Sepal.Width = "numeric",
      Petal.Length = "numeric",
      Petal.Width = "numeric",
      Species = "factor"
    )
  ) %>%
  interrogate()

agent
