---
title: Acelera tu programación con {gander}, un asistente de IA integrado en RStudio
author: Bastián Olea Herrera
date: '2025-10-18'
draft: true
slug: []
categories: []
tags:
  - inteligencia artificial
  - consejos
format:
  hugo-md:
    output-file: index
    output-ext: md
links: 
  - icon: github
    icon_pack: fab
    name: Gander
    url: https://simonpcouch.github.io/gander/
  - icon: book
    icon_pack: fas
    name: LLMs en R
    url: https://luisdva.github.io/llmsr-book/r-pkgs.html
execute: 
  eval: false
---

{{< indice >}}

https://simonpcouch.github.io/gander/


La idea principal es que puedes seleccionar tu código o texto en R, y presionar una combinación de teclas para elegir tu asistente. Dependiendo del tipo de asistente, se agregará código arriba o abajo de lo que seleccionaste, o bien, se va a reemplazar lo que seleccionaste por lo que haga el asistente.


Dos opciones 

## Instalar un modelo de lenguaje local desde R
Como este paquete depende de el uso de un modelo de lenguaje para funcionar, necesitas tener instalado un modelo de lenguaje en tu equipo, o tener una suscripción a un modelo de lenguaje en la nube. Personalmente prefiero usar un modelo de lenguaje local: [Llama 3.1](https://ollama.com/library/llama3.1) con 8 billones de parámetros. Para instalar un modelo localmente en tu equipo desde R, primero tienes que [instalar Ollama en tu equipo](https://ollama.com), abrir la aplicación, y luego [instalar el paquete de R {ollamar}](https://hauselin.github.io/ollama-r/) para descargar un modelo de lenguaje local desde R.[^1]

[^1]: Si tu computador no es muy poderoso, te recomiendo instalar `llama3.2:1b` (más liviano) o `llama3.2:3b` (un poco mejor), pero si tienes suficiente memoria y tarjeta de video, puedes instalar `llama3.1:8b`.

Si no tienes un modelo instalado, usa este comando para descargar e instalar un modelo desde R:
```r
library(ollamar)
pull("llama3.1:8b")
```
Es necesario tener la aplicación Ollama abierta en tu computadora, dado que ésta aplicación es la que le entrega el modelo de lenguaje a R.


## Configurar un proveedor de IA



----

Para más paquetes y herramientas de modelos de lenguaje e IA en R, revisa [Large Language Model tools for R](https://luisdva.github.io/llmsr-book/), de Luis D. Verde Arregoitia.