---
title: Creando colores con R
author: Basti치n Olea Herrera
date: '2025-03-06'
format:
  hugo-md:
    output-file: "index"
    output-ext: "md"
slug: []
categories: []
tags:
  - visualizaci칩n de datos
  - gr치ficos
  - ggplot2
---




Paletas secuenciales
```{r}
paleta_secuencial <- c("#f4b43f", "#ec6a2d", "#cc3b7b", "#705ce6", "#668cf6")

swatch(paleta_secuencial)


# estirar colores
colorRampPalette(paleta_secuencial)(12) |> swatch()

colorRampPalette(c("#df65b2", "#fae55f"))(8) |> swatch()
```



M치s paletas
```{r}
RColorBrewer::display.brewer.all()
```


```{r}
colorspace::hcl_palettes(plot = TRUE)
```

```{r}
colorspace::qualitative_hcl(5, palette = "Set 3") |> swatch()
```

```{r}
colorspace::sequential_hcl(5, palette = "Red-Blue") |> swatch()

colorspace::sequential_hcl(5, palette = "Purple-Orange") |> swatch()
```


Paletas divergentes
```{r}
paleta_divergente <- colorspace::diverging_hcl(n = 5, 
                                               h = c(200, 300)
)


shades::swatch(paleta_divergente)

```



Usar paletas
```{r}
library(ggplot2)
library(dplyr)

iris |> 
  ggplot() +
  geom_bar(aes(Petal.Width, fill = Species)) +
  colorspace::scale_fill_discrete_qualitative(palette = "Dark 3") +
  scale_y_continuous(expand = expansion(c(0, 0.1))) +
  theme_classic()


iris |> 
  ggplot() +
  geom_point(aes(Sepal.Width, Sepal.Length, color = Petal.Width, size = Petal.Length), alpha = .8) +
  colorspace::scale_color_continuous_sequential(palette = "Sunset", na.value = "white") +
  theme_classic() +
  guides(size = guide_legend(override.aes = list(color = "#784FA1")),
         color = guide_colorsteps()) +
  theme(legend.title = element_blank(),
        axis.title = element_blank())
```


Modificar colores
```{r}

library(shades)

"#f65b74" |> swatch()


brightness("#f65b74", 0.7)

# obtener el hue
hue("#f65b74")


"#f65b74" |> hue(delta(30)) |> swatch()


"#f65b74" |> lightness(delta(30)) |> swatch()

swatch(
  c("#f65b74" |> chroma(delta(30)), 
    "#f65b74",
    "#f65b74" |> chroma(delta(-30)))
)

"#f65b74" |> saturation(delta(30))
```



```{r}
color_principal = "#4D4484"

color_fondo = color_principal |> lightness(13) |> chroma(20)
color_detalle = color_principal |> lightness(20) |> chroma(40)
color_destacado = color_principal |> lightness(50) |> chroma(65)
color_texto = color_principal |> lightness(80)

swatch(c(color_principal,
         color_fondo,
         color_detalle,
         color_destacado,
         color_texto))

color_principal = "#3170ac"

color_fondo = color_principal |> lightness(13) |> chroma(20)
color_detalle = color_principal |> lightness(20) |> chroma(40)
color_destacado = color_principal |> lightness(50) |> chroma(65)
color_texto = color_principal |> lightness(80)

swatch(c(color_principal,
         color_fondo,
         color_detalle,
         color_destacado,
         color_texto))

```


mezclar colores
```{r}
swatch(c("#70f1d5",
         submix("#70f1d5", "#fae55f"),
         "#fae55f"))
```
```{r}
swatch(c("#3377f7",
         addmix("#3377f7", "#ec4e3c"),
         "#ec4e3c"))
```

```{r}
swatch(c("#f9ce45",
         submix("#f9ce45", "#77d671", amount = 0.5),
         "#77d671"))
```




- https://github.com/EmilHvitfeldt/r-color-palettes
- https://r-graph-gallery.com/ggplot2-color.html
- https://www.datanovia.com/en/blog/top-r-color-palettes-to-know-for-great-data-visualization/
- https://jbengler.github.io/tidyplots/articles/Color-schemes.html